### ISSUE TITLE
YAML 1.2 typo "as as"

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#10]
Hi,

In section "5.2 Character Encodings" 4th paragraph, "as" is repeated in "to be as as indicated".

Best regards,
  Laurent Lyaudet

**Comment by ingydotnet** [comment]
Fixed by 4df0ea6

**Comment by ingydotnet** [comment]
Fixed again in 15a7f93257fcb98dfe42c1c4c6b0851bb98b7aa1
