### ISSUE TITLE
[meta] Cannot start a new discussion on GitHub

### ISSUE THREAD

**Issue by am11** [yaml/yaml-spec#111]
Navigating to the following link https://github.com/yaml/yaml-spec/discussions/new results in an error:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/3840695/129910340-bf169d88-ac8a-4795-8944-7a842eb51616.png">

**Comment by ingydotnet** [comment]
We're not using discussions quite yet. The #113 issue is fine.
