### ISSUE TITLE
YAML 1.2 Example 7.16 wrong caption/legend

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#13]
Hi,

In "Example 7.16 Flow Mapping Entries" it seems to me that the lines/dashes around the tokens are exchanged between the example and the legend/caption.
"ns-flow-map-explicit-entry(n,c)" should be "ns-flow-map-implicit-entry(n,c)" and vice-versa.

Best regards,
  Laurent Lyaudet

**Comment by ingydotnet** [comment]
Fixed in 3e20bd46338cc8947615c629307dc1be47692045
