### ISSUE TITLE
YAML 1.2 Rules [154] and [155] n/a

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#14]
Hi,

In rules [154] and [155] What is "a" in "n/a" ?
Is it a typo ? Or else can you add an explanation, please ?

Best regards,
  Laurent Lyaudet

**Comment by orenbenkiki** [comment]
"n/a" means "Not Applicable".

**Comment by LLyaudet** [comment]
Hi,

Thanks for the answer. It is quite unfortunate that the place where there is 'n/a' is exactly the place that would contain 'n' in other rules.

Best regards,
  Laurent Lyaudet

**Comment by yaurthek** [comment]
Hello, I just came across this thread after managing to find out what this "n/a" meant on my own.

I had to spend a few hours reading the haskell reference implementation to do so... (I'm not familiar with haskell)

Clarifying this point in the spec would be greatly appreciated!

(By the way, thanks a lot for the haskell reference implementation, it's fantastic, almost magical to me at the moment :) )

**Comment by ingydotnet** [comment]
Fixed in 165fee132de3d5275000d0874e50bcc6a4791c47
