### ISSUE TITLE
YAML 1.2 Example 8.2 indentation indicator

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#16]
Hi,

According to section "8.1.1.1" the indentation indicator is relative to the indentation level of the parent node.
For me, in "Example 8.2" the parent node is the "seq" with indentation level 0.
Hence, the indentation indicator for "explicit" should be 2 instead of 1.
Am I correct ? If not, where do I make an error ?

Best regards,
  Laurent Lyaudet

**Comment by eemeli** [comment]
The value of the block scalar in question is " explicit", i.e. it has a leading space. The first space on that line is taken by the indentation due to the explicit "1" level, the second is a part of the scalar value.

**Comment by ingydotnet** [comment]
The explicit indentation _could_ be 1 or 2, but in this example the semantics match the value `1` used.
