### ISSUE TITLE
YAML 1.2 Section 10.2.1.4 regular expression and pdf

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#21]
Hi,

In section "10.2.1.4" "Canonical Form" Is-it possible to put the regular expression on its own line for the pdf (it's fine for the html).

Best regards,
  Laurent Lyaudet

**Comment by ingydotnet** [comment]
Fixed in 1a21e14f0dd32b9764721a69c81baae7be2a8241
