### ISSUE TITLE
YAML 1.2 JSON vs YAML and "one-pass double-validation"

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#23]
Hi,

You write "The order of alternatives inside a production is significant. [...]"
It appears that the JSON alternative is listed last in a few cases. Is-it intentional?
I thought that it would be listed first since it's more restrictive and it would enable "one-pass double-validation"
(the document is valid YAML 1.2 and is also valid JSON or not).
 Example : rule [158] YAML is before JSON. However in "Example 7.23 Flow Content" the tokens are "legended/captioned" in priority with "c-flow-json-content(n,c)"
instead of "ns-flow-yaml-content(n,c)". idem for "Example 7.24 Flow Nodes".

Best regards,
  Laurent Lyaudet

**Comment by orenbenkiki** [comment]
In this case it doesn't matter since you can tell by the 1st character whether something is a plain scalar; the order rule only applies when there's some element of choice.

**Comment by LLyaudet** [comment]
Hi,

Thanks for the precision.

Best regards,
  Laurent Lyaudet
