### ISSUE TITLE
Broken link to pdf and ps YAML 1.2 specs on yaml.org/spec/ page

### ISSUE THREAD

**Issue by wedaly** [yaml/yaml-spec#245]
On [https://yaml.org/spec/](https://yaml.org/spec/), the links to the pdf and ps versions under "YAML latest patched specification (final YAML 1.2)" return a 404 not found from GitHub pages:

* https://yaml.org/spec/1.2/spec.pdf
* https://yaml.org/spec/1.2/spec.ps

I see [a comment on issue 22](https://github.com/yaml/yaml-spec/issues/22#issuecomment-899091221) mentioning that PDFs are no longer being published -- should the links in the index page be removed?

**Comment by ingydotnet** [comment]
This is actually an issue in https://github.com/yaml/www.yaml.org/

Fixed. Thanks.
