### ISSUE TITLE
Add link from yaml.org/spec to here + Update errata

### ISSUE THREAD

**Issue by eemeli** [yaml/yaml-spec#27]
As it appears that this version of the YAML 1.2 spec is more up to date than the one available at http://www.yaml.org/spec/1.2/spec.html, it would be beneficial if the version there could refer to this, rather than presenting itself as the sole authoritative source.

Furthermore, it would be good if the typos and other mistakes that have been corrected in this repo could be made available somewhere in published form.

**Comment by perlpunk** [comment]
A while ago, there was an attempt to regenerate the Spec, but it has the problem that all numeric link ids will get assigned new ids, so links pointing to the old version will get invalid (point to non-existing or the wrong targets).
I made a quick and dirty script which tries to keep links by looking at the old version, but it didn't catch all cases.
The only clean solution would be to publish it as 1.2.1 or something...

**Comment by eemeli** [comment]
Given that this version of the spec doesn't get updated all that often, it might be feasible to look at the diff of changes from the last-published version to the current one, and apply those manually to the published version. Which I believe would be [this set of changes](../compare/a9064f3...master)?

**Comment by eemeli** [comment]
Closing as out of date, given the current RFC process for YAML 1.5.
