### ISSUE TITLE
Serialization tree versus serialization events

### ISSUE THREAD

**Issue by Thom1729** [yaml/yaml-spec#42]
The spec defines the “Serialization Tree” as one of the three information models for a YAML document. However, sometimes the spec refers to “a series of serialization events”. This latter notion doesn't seem to be clearly defined in the spec.

The closest thing to a definition seems to be §3.1.1:

> The result of this process, a YAML serialization tree, can then be traversed to produce a series of event calls for one-pass processing of YAML data.

In §3.1.2, parsing and composing are defined to work on series of serialization events, not on a serialization tree:

> Parsing is the inverse process of presentation, it takes a stream of characters and produces a series of events.
> …
> Composing takes a series of serialization events and produces a representation graph.

The spec does not say what types of serialization events there are or what information they carry. The YAML test suite uses the notion in many of its test cases, but [it is unclear](https://yaml.org/spec/1.2/spec.html#id2765410) where their notation comes from or exactly what it refers to. It seems to be an “enclosing-order” traversal of a representation tree where scalar nodes are represented by one event and collection nodes are represented by separate start and end events. A syntax error in the YAML stream can result in a partial event stream.

Am I missing something?

**Comment by ingydotnet** [comment]
@Thom1729,

This is a topic that vexes me. I'm not certain why we talk about the concept of an event _tree_.
In my mind (and in most full stack implementations I've seen) a YAML parser transforms a stream of tokens into a stream of events.

A YAML stack looks something like:
```
    Load Stack         Dump Stack
    ----------         ----------
               (File)
     |        /       \        ^
     |    read         write   |
     v        \       /        |
               (Chars)
              /       \
           lex         join
              \       /
               (Tokens)
              /       \
         parse         emit
              \       /
               (Events)
              /       \
       compose         serialize
              \       /
                (DOM)
              /       \
     construct         represent
              \       /
               (Native)
```

I'm planning to write some rather complete documentation on the YAML Stack. This would include detailed explanations of the type of information that belongs in an event.

Currently we are working on publishing a YAML 1.2.1 spec to fix errata and add clarity. A draft is here: https://ingydotnet.github.io/yaml-spec/spec

We recently made this interactive tool to show the events produced by many YAML parsers: https://ingydotnet.github.io/yaml-spec/playground/parser

As you can see, events are clearly a stream. I think I'll make a PR for the 1.2.1 spec to change the wording to reflect that.
