### ISSUE TITLE
Binary data needs human-readable encoding

### ISSUE THREAD

**Issue by smurfix** [yaml/yaml-spec#50]
Hello,
the strict distinction of string vs. binary data in YAML is very welcome and helpful, but its limitation on `!!binary` as base64-encoded data is not. Some binary data is in fact plain ASCII and should be representable as such within YAML.

**Comment by eemeli** [comment]
Could you give an example of the sort of data you'd want to represent in YAML?

**Comment by smurfix** [comment]
File names for instance. They're not guaranteed to be UTF-8, esp. on older systems, thus you need a binary representation.

I am writing a logger for MQTT data. These are encoded in msgpack (which has a strict string/binary distinction) and displayed to the user in YAML. After the user edits a message (or not) I need to be able to reinject them. The editor is external and I cannot teach it base64.

**Comment by pantoniou** [comment]
As a note, YAML *is* capable of encoding arbitrary data as double quoted strings with
appropriate escapes. For example the 32 bit value `0xdeadbeef` is perfectly encoded
as `"\xde\xad\xbe\xef"`. The encoding is not very space efficient, but 
Whether this roundtrips correctly in your YAML stack is a different matter.

There are two kinds of binary data pertinent to YAML.

1. Arbitrary binary data, for example crypto keys, which do not have any relationship with textual data. Typically they can be quite large.

2. Data which are textual in nature but may contain some parts which may not be represented using the regular UTF-8 character set.

For #1 base64 encoding is natural. I'm not sure if there's an new method that could use the whole UTF-8 character set and it's encoding semantics for something more compact. 

For #2 YAML double quoted strings work fine, although are not the most efficient.

To demonstrate I'm including a small libfyaml example that generates and emits binary data.

```c
/*
 * binary.c - libfyaml binary YAML example
 *
 * Copyright (c) 2020 Pantelis Antoniou <pantelis.antoniou@konsulko.com>
 *
 * SPDX-License-Identifier: MIT
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdlib.h>
#include <stdio.h>
#include <assert.h>

#include <libfyaml.h>

int main(int argc, char *argv[])
{
	static const uint8_t binary_data[] = {
		0x00, 0x01, 0x02, 0x03,
		0x40, 0x41, 0x43, 0x44,
		0xfc, 0xfd, 0xfe, 0xff
	};
	struct fy_document *fyd = NULL;
	struct fy_node *fyn;
	int rc, ret = EXIT_FAILURE;

	fyd = fy_document_create(NULL);
	if (!fyd) {
		fprintf(stderr, "failed to create document");
		goto fail;
	}

	fyn = fy_node_create_scalar(fyd, (const char *)binary_data, sizeof(binary_data));
	if (!fyn) {
		fprintf(stderr, "failed to create binary data scalar node");
		goto fail;
	}

	rc = fy_document_set_root(fyd, fyn);
	if (rc) {
		fprintf(stderr, "failed to set document root\n");
		goto fail;
	}

	/* emit the document to stdout */
	rc = fy_emit_document_to_fp(fyd, FYECF_DEFAULT, stdout);
	if (rc) {
		fprintf(stderr, "failed to emit document to stdout");
		goto fail;
	}
	ret = EXIT_SUCCESS;
fail:
	fy_document_destroy(fyd);	/* NULL is OK */

	return ret;
}
```

The resulted output is:

```
"\0\x01\x02\x03@ACD\xFC\xFD\xFE\xFF"
```

Note how the binary data that correspond to displayable characters are output as is `@ACD`, `0x00` is output as `\0` and the rest as hexadecimal \x escapes.

**Comment by smurfix** [comment]
The fact is that there are programming languages, such as Python, and codecs such as MsgPack, who have a hard distinction between UTF-8 strings and binary arrays-of-arbitrary bytes.

A YAML quoted string is exactly that – a quoted string. It may not be UTF8 when you naïvely parse it in C, but in Python that \xFF will end up as ÿ (or 0xC3 0xBF in utf8-ese). Thus if you want to reproduce it you have to magically know that you need to encode it to binary with iso-8859-1, instead of to a string with utf-8. I'd like to replace that magic with a standardized YAML tag.

While I could, and in fact will, create my own special type for such a bytes-displayed-as-ASCII type – in order to support my logger and my editor – that's nonstandard and I'd have to convince everybody else to support it. Not good. I'd rather use something like `!!binstr` or `!!bytestr`, and ask people to simply update their YAML library to 1.3. Whenever that gets finished.

**Comment by pantoniou** [comment]
This all seems like a problem addressed by your combination of implementation language and YAML middleware, which could be updated with an binary data type.

python internal limitations are not relevant to the core YAML spec IMHO.

**Comment by smurfix** [comment]
Why should a strict divide between strings and arrays of bytes be considered an "internal limitation"? I'd rather state that C's/Javascript's/JSON's limitation is its inability to distinguish between the two in a meaningful way.

**Comment by eemeli** [comment]
YAML itself is defined in terms of Unicode code points, much like JSON is. Encoding a string within YAML that uses a different encoding than its surroundings sounds likely to create interesting errors down the line.

It sounds like you have two pieces of data that need to be stored at the same time: The file name as a string, and its encoding. Would it make sense in your application to store those separately in your YAML file?

**Comment by eemeli** [comment]
... but I suspect your problem is that you don't want to need to know what that original encoding is, and you just want to have this string-ish data pass through YAML without alteration, yes?

This sounds exactly like the sort of problem for which a local application-specific tag can provide a good answer. As you may be aware, `!!binary` is not a part of any of the YAML 1.2 default schemas, and support for it is likely to be library-specific. The current set of core schema tags is actually rather small. It's unlikely that we'll be expanding those for 1.3.

I would recommend that you proceed with writing your own local tag implementation, which is likely to be relatively small, and to then submit that for inclusion in the YAML library that you're using. If others pick it up, it may eventually make sense to include it in a later version of the whole language.

**Comment by smurfix** [comment]
Fair enough. Closing this for now.
