### ISSUE TITLE
YAML 1.2 typo "; In contrast"

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#6]
Hi,

In section "3.2.3.1 Node Styles" on line 2 the semicolon is followed by a capital letter "; In contrast".
  I'm not a native english speaker but I have found there:
  http://www.grammarly.com/handbook/punctuation/semicolon/1/semicolon-use/
  that there shouldn't be a capital letter.

Best regards,
  Laurent Lyaudet

**Comment by ingydotnet** [comment]
Fixed by 2443ff3
