### ISSUE TITLE
Discuss: RFC-0001 - Empty-scalars not allowed as keys

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yaml-spec#71]
RFC: https://github.com/yaml/yaml-spec/tree/master/rfc/RFC-0001.md

See: https://github.com/yaml/yaml-spec/tree/master/rfc/ReadMe.md

**Comment by eemeli** [comment]
Are empty scalars also not allowed as explicit mapping keys? As in, would a source string consisting of a single `?` cause an error, or be parsed as a mapping with a single `null: null` pair?

**Comment by ingydotnet** [comment]
Locked until we flesh out and document the RFC process more.

**Comment by ingydotnet** [comment]
See: https://github.com/yaml/yaml-spec/wiki/YAML-RFC-Process

Closing this until we formalize the RFC process.
