### ISSUE TITLE
Discuss: RFC-0005 - Directives belong to the stream and not a document

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yaml-spec#79]

**Comment by eemeli** [comment]
Link to this RFC: https://github.com/yaml/yaml-spec/blob/master/rfc/RFC-0005.md

I just realised that the proposal does not explicitly specify that defining _any_ directives between documents effectively resets _all_ directives, as is done in YAML 1.1. Thinking about it now, I'm not sure that really makes sense. Why not just let each directive be treated independently, and have it just modify the current state? That does make concatenating documents a bit more difficult, if they may be prefixed by directives, but I'm not sure that's really an actual issue.

**Comment by ingydotnet** [comment]
Locked until we flesh out and document the RFC process more.

**Comment by ingydotnet** [comment]
See: https://github.com/yaml/yaml-spec/wiki/YAML-RFC-Process

Closing this until we formalize the RFC process.
