### ISSUE TITLE
YAML 1.2 tab in nb-json

### ISSUE THREAD

**Issue by LLyaudet** [yaml/yaml-spec#9]
Hi,

In section "5.1 Character Set" Maybe I've misunderstood something but you say explicitly that "JSON quoted scalars cannot [...] contain tabs".
Nevertheless, you list tab "#x9" in rule [2] that defines nb-json. Should-it be renamed "nb-yaml" or should the "#x9" be removed?
If not, can you clarify please?

Best regards,
  Laurent Lyaudet

**Comment by ingydotnet** [comment]
Just getting around to open issues here...

This one is a bit confusing. Here's my stab at it.

There are characters in the non (C0) control range `[#x20-#x10FFFF]` that YAML would have omitted if not for JSON compatibility. (The C1 control range for example).

YAML does allow literal `x09` tab characters, so the rule for non-break characters is:
```
[2] nb-json ::=
  #x9 | [#x20-#x10FFFF]
```

I agree that the name `nb-json` is not great. I think `mb-characters` is more appropriate.

I'll attempt to clarify in the upcoming 1.2.1 spec, but the production name change will need to wait until 1.3.
